LOAD
;$CBFE
INITLOAD    = $06FE
LARGOLOAD   = [.LEN PAGINALOAD]
LOGOLOAD	= [[PAGINALOAD.MENSAJELOAD - PAGINALOAD] + LOAD]
TITULOOOPCIONALLOAD = [[PAGINALOAD.TITULOOOPCIONALLOAD - PAGINALOAD] + LOAD]
TITULOARCHIVOLOAD   = [[PAGINALOAD.TITULOARCHIVOLOAD - PAGINALOAD] + LOAD]
BLOQUESLOADER       = [[PAGINALOAD.BLOQUESLOADER - PAGINALOAD] + LOAD]
.PROC PAGINALOAD,INITLOAD
;SAVE#D:PAGLOAD.ASM
;    *=  $CBFE
BUFFERLOAD  = FINLOAD+1
INICIOLOAD
    .BYTE $55,$55
    LDY #$00
    STY $0244   ;COLDST
    INY 
    STY $09     ;BOOT
    JSR LIMPIOBANQUEOLOAD
    JMP STARTLOAD
LIMPIOBANQUEOLOAD
    LDX #39
    LDA #$00
LIMPIOBANQUEOLOAD01
    STA BANQUEOLOAD,X
    STA BANQUEOLOAD+40,X
    STA BANQUEOLOAD+80,X
    STA BANQUEOLOAD+120,X
    STA BANQUEOLOAD+160,X
    STA BANQUEOLOAD+200,X
    STA BANQUEOLOAD+240,X
    DEX
    BPL LIMPIOBANQUEOLOAD01
    RTS
DLSLOADER
    .BYTE $70,$70,$70,$46
    .WORD MENSAJELOAD
    .BYTE $70,$02,$70
    .BYTE $02,$02,$02,$02,$02
    .BYTE $02,$02
    .BYTE $70,$70,$70,$70,$06,$70,$06
    .BYTE $70,$70,$70,$02
    .BYTE $41
    .WORD DLSLOADER
MENSAJELOAD
    .SB "                    "
    .SB " PROGRAMAS PARA COMPUTADORES ATARI 2025 "
BANQUEOLOAD
    .SB "**************************************40"
    .SB "**************************************80"
    .SB "*************************************120"
    .SB "*************************************160"
    .SB "*************************************200"
    .SB "*************************************240"
    .SB "*************************************280"
TITULOOOPCIONALLOAD
    .SB "--ACA VA EL TITULO--"
TITULOARCHIVOLOAD
    .SB "--ACA VA EL TITULO--"
    .SB "     Quedan "
BLOQUESLOADER
    .SB "**** bloques restantes.     "
CDLLOADER
    LDX # <DLSLOADER
    LDY # >DLSLOADER
    STX $0230   ;SDLSTL
    STX $D402   ;DLISTL
    STY $0231   ;SDLSTH
    STY $D403   ;DLISTH
    LDA #$60    ;$02C8
    STA $02C6   ;COLOR2
    STA $02C8   ;COLOR4
    STA $D018   ;COLPF2
    RTS 
STARTLOAD
    JSR CDLLOADER
LOOPLOAD

    JMP LOOPLOAD
FINLOAD
.ENDP