PAG4
;SAVE#D:PAGINA4.ASM
;    *=  $03FD
LARGOPAGINA4    = [.LEN PAGINA4]
.PROC PAGINA4,$03FD
    .BYTE $55,$55,$FE
    LDA $D301
    AND #$02
    BEQ ERRORPAG4
    LDX #$0B
MOVEPAG4
    LDA PAG4SIOV,X
    STA $0300,X
    DEX 
    BPL MOVEPAG4
    JSR $E459   ;SIOV
    BMI ERRORPAG4
    ;LDA FINPAG4
    ;STA $47     ;GENDAT
    CLC 
    RTS 
ERRORPAG4
    LDX $CFFC
    LDY $CFFD
    STX $0230   ;SDLSTL
    STY $0231   ;SDLSTH
    LDY #$00
LERPAG4
    LDA TABLAPAG4,Y
    STA ($58),Y
    INY 
    CPY #$1B
    BNE LERPAG4
    LDA #$3C
    STA $D302   ;PACTL
LOOPPAG4
    JMP LOOPPAG4
TABLAPAG4
    .SB "ERROR !!! CARGUE NUEVAMENTE"
PAG4SIOV
    .BYTE $60,$00,$52,$40
    .WORD INITLOAD ;CARGA LOAD
    .BYTE $23,$00
    .WORD LARGOLOAD ;LARGO LOAD
    .BYTE $00,$80
FINPAG4
.ENDP