
LLOAD 	= PAG7-LOAD
LAUTO 	= PAG4-PAG7
BL4 	= LAUTO/128
LAST 	= LAUTO-128*BL4
;************************************************
;GENERA UNA PAUSA DE X SEGUNDOS YA PREDEFINIDOS
;ANTERIORMENTE EN UNA VARIABLE X
;************************************************
PAUSITA
	STX $021C
?PAUSITA
	LDX $021C
	BNE ?PAUSITA
	RTS
;************************************************
;FUNCION QUE INICIA EL SIOV PARA GRABAR DATA EN
;LA CINTA
;************************************************
INITSIOV
	LDY #$0B
?INITSIOV
	LDA DNHP,Y
	STA $0300,Y
	DEY
	BPL ?INITSIOV
	LDA #$00
	STA 77		;$4D
	RTS
DNHP
	.BYTE $60,$00,$52,$80
	.WORD BANQUEO
	.BYTE $35,$00
	.WORD $0100
	.BYTE $00,$80
;************************************************
;FUNCION QUE NOS PERMITE ABRIR EL PERIFERICO
;CASETERA ESPERANDO QUE SE PRESIONE RETURN
;************************************************
OPENC
	LDA VCOUNT
	BNE OPENC
	LDA #$FF
	STA 764
?OPENC
    LDA #$00
    STA 77
	LDA 764
	CMP #$FF
	BEQ ?OPENC
	JSR ESMENSAJEINICIANDO
	LDA #$FF
	STA 764
	JMP $FD40	;AUDIO ATENUACION
ENCRIPTOPAGINA7
    LDX #TOTALENCRIPTADOPAGINA7
ENCRIPTOPAGINA701
	CLC
    LDA STACENCRIPT,X
    ADC #$12 ;$FD
    STA STACENCRIPT,X
    DEX
    BPL ENCRIPTOPAGINA701
	RTS
AUTORUN
	JSR ESMENSAJEPAGINA7
	LDX # <PAG7
	LDY # >PAG7
	LDA #$02	;02 graba 3 bloques en cinta
	STX MVPG7+1
	STY MVPG7+2
	STA RY
FALTA
	JSR INITSIOV
	LDX #<BANQUEO	;??DIR
	LDY #>BANQUEO	;??DIR
	STX $0304
	STY $0305
	LDX #131		; $83
	LDY #$00		; $00
	STX $0308
	STY $0309
	LDY #$00
	TYA
CLBUF
	STA BANQUEO,Y		;??DIR,Y
	INY
	CPY #131		;$83
	BNE CLBUF
	LDA #$55
	STA BANQUEO			;??DIR
	STA BANQUEO+1		;??DIR+1
	LDX #$FC
	LDY #127	;$7F
	DEC RY
	BPL NOFIN
	LDX #$FA
	LDY #LAST
	STY BANQUEO+130		;??DIR+130
NOFIN
	STX BANQUEO+2		;??DIR+2
MVPG7
	LDA PAG7,Y
	STA BANQUEO+3,Y 	;??DIR+3,Y
	DEY
	BPL MVPG7
	JSR $E459
	CLC
	LDA MVPG7+1
	ADC #$80
	STA MVPG7+1
	LDA MVPG7+2
	ADC #$00
	STA MVPG7+2
	LDA RY
	BPL FALTA
	RTS
GAUTO
	JSR LIMPIORY
	JSR LIMPIOBANQUEO
	JSR ENCRIPTOPAGINA7
	LDA #$FF
	STA $D301
	JSR BAUD.600
;GRABAMOS LOS 3 PRIMEROS BLOQUES
	JSR AUTORUN
	JSR INITSIOV
	JSR ESMENSAJEPAGINA4
;GRABAMOS EL 4TO BLOQUE
	LDX # <131		;GRABA EL 4 BLOQUE CON LA INFORMACION
	LDY # >131		;QUE CARGARA EL LOADER 
	STX $0308
	STY $0309
	LDX # <PAG4
	LDY # >PAG4
	STX $0304
	STY $0305
	JSR $E459
	JSR INITSIOV
	LDX #$40		;GENREAMOS UNA PEQUEÑA PAUSA PARA QUE SE
	JSR PAUSITA		;ACTIVE LA ROM A RAM DE LA PAGINA7
;VALIDAMOS SI ES A 600 O 800 BAUDIOS
	LDA SISTEMA
	CMP #$00
	BEQ GAUTOLOADER
;SI ES A 800 CAMBIAMOS LA VELOCIDAD DE GRABACION
	JSR BAUD.800
;GRABAMOS EL LOADER
GAUTOLOADER
	JSR ESMENSAJEPAGINALOAD
	LDX # <LARGOLOADER	;GRABAMOS EL LOADER EN PANTALLA
	LDY # >LARGOLOADER
	STX $0308
	STY $0309
	LDX # <LOAD
	LDY # >LOAD
	STX $0304
	STY $0305
	JSR $E459
;GRABAMOS EL ARCHIVO
    RTS