    ICL 'sys_equates.m65'
    ICL 'sys_macros.m65'
    ORG $700
    INS 'mydos.dat'
MYDOS
    JSR $07E0
    RTS
    INI MYDOS
    ORG $2000
    ICL 'paginas.asm'
    ICL 'funciones.asm'
DISPLAY
:3  .BY $70
    .BY $46
    .WO SHOW
:14  .BY $02
:8    .BY $02
    .BY $41
    .WO DISPLAY
SHOW
:20 .SB " "
    .SB +32,"QRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRE"
    .SB "|  DOGDARK MULTIBANCOS NHP 3.0 - 2025  |"
    .SB +32,"ARRRRRRRRRRRRRRRWRRRRRRRRRRRRRRRRRRRRRRD"
    .SB "|MEMORIA        |              "
MEMORIAPR
    .SB "******* |"
    .SB "|BANCOS DISPO.  |                   "
BANCOSPR
    .SB "** |"
    .SB "|PORTB EN USO   |                  $"
PORTBPR
    .SB "** |"
    .SB "|VELOCIDAD      |          "
BAUDIOSPR
    .SB "600 BAUDIOS |"
    .SB "|BYTES X BLOQUES|            "
BYTESPR
    .SB "251 BYTES |"
    .SB "|BYTES LEIDOS   |              "
BYTESLEIDOSPR
    .SB "******* |"
    .SB "|BLOQUES GRABAR |       "
BLOQUESLEIDOSPR
    .SB "**** RESTANTES |"
    .SB "|TITULO ARCHIVO | "
TITULOARPR
    .SB "******************** |"
    .SB "|TITULO OPCIONAL| "
TITULOOPPR
    .SB "******************** |"
    .SB "|FUENTE         | "
FUENTEPR
    .SB "******************** |"
    .SB +32,"ZRRRRRRRRRRRRRRRXRRRRRRRRRRRRRRRRRRRRRRC"
BANQUEO
    .SB "INICIO BANQUEO**************************"  ;40
    .SB "****************************************"  ;80
    .SB "****************************************"  ;120
    .SB "****************************************"  ;160
    .SB "****************************************"  ;200
    .SB "****************************************"  ;240
    .SB "*****************************FIN BANQUEO"  ;280
MENSAJES
:40    .SB +128," "
MENSAJEINICIO
    .SB +128,"SELECT [BYTES BLOQUES]  OPTION [BAUDIOS]"
MENSAJECARGANDO
    .SB +128,"      CARGANDO ARCHIVO EN MEMORIA.      "
MENSAJERETURN
    .SB +128,"  PRESIONE RETURN PARA GRABAR ARCHIVO.  "
MENSAJEINICIANDO
    .SB +128,"          INICIANDO GRABACION           "
MENSAJEPAGINA7
    .SB +128,"            GRABANDO PAGINA7            "
MENSAJEPAGINA4
    .SB +128,"            GRABANDO PAGINA4            "
MENSAJELOADER
    .SB +128,"            GRABANDO  LOADER            "
MENSAJEARCHIVO
    .SB +128,"        GRABANDO ARCHIVO A CINTA        "
MENSAJEFINGRABACION
    .SB +128,"         FIN GRABACION DE CINTA         "
ES128
    .SB "128"
ES253
    .SB "251"
ESSTANDART
    .SB "600"
ESSTAC
    .SB "800"
SISTEMA
    .BY $00 
ARMOLOGO
    LDX #19
ARMOLOGO01
    LDA DATADISPLAY,X
    STA SHOW,X
    STA LOGOPAGINA7,X
    STA TITULOLOGO,X
    DEX
    BPL ARMOLOGO01
    RTS
;FUUNCIONES DE LIMPIEZA
LIMPIOBANQUEO
    LDA #$00
    LDX #39
LIMPIOBANQUEO01
    STA BANQUEO,X
    STA BANQUEO+40,X
    STA BANQUEO+80,X
    STA BANQUEO+120,X
    STA BANQUEO+160,X
    STA BANQUEO+200,X
    STA BANQUEO+240,X
    DEX
    BPL LIMPIOBANQUEO01
    RTS
LIMPIOTITULO
    LDA #$00
    LDX #19
LIMPIOTITULO01
    STA TITULOARPR,X
    DEX
    BPL LIMPIOTITULO01
    RTS
LIMPIOOPCIONAL
    LDA #$00
    LDX #19
LIMPIOOPCIONAL01
    STA TITULOOPPR,X
    DEX
    BPL LIMPIOOPCIONAL01
    RTS
LIMPIOFUENTE
    LDA #$00
    LDX #19
LIMPIOFUENTE01
    STA FUENTEPR,X
    DEX 
    BPL LIMPIOFUENTE01
    RTS
LIMPIOBYTES
    LDA #$00
    STA BYTES
    STA BYTES+1
    STA BYTES+2
    RTS
LIMPIOBLOQUES
    LDA #$00
    STA BLOQUES
    STA BLOQUES+1
    RTS
LIMPIORY
    LDA #$00
    STA RY
    STA RY+1
    STA RY+2
    RTS
ESPORTB
    JSR LIMPIOVAL
    LDA PORTB
    STA VAL
    JSR BIN3BCD
    LDA HEXATASCII+3
    STA PORTBPR+1
    LDA HEXATASCII+2
    STA PORTBPR
    RTS
ESBANCOS
    JSR LIMPIOVAL
    LDA BANKOS
    STA VAL
    JSR BIN2BCD
    LDA RESATASCII+7
    STA BANCOSPR+1
    LDA RESATASCII+6
    STA BANCOSPR
    RTS
ESMEMORIA
    JSR LIMPIOVAL
    LDA MEMORIA
    STA VAL
    LDA MEMORIA+1
    STA VAL+1
    LDA MEMORIA+2
    STA VAL+2
    JSR BIN2BCD
    LDY #7
    LDX #6
ESMEMORIA01
    LDA RESATASCII,Y
    STA MEMORIAPR,X
    DEY
    DEX
    BPL ESMEMORIA01
    RTS
ESBYTESLEIDOS
    JSR LIMPIOVAL
    LDA BYTES
    STA VAL
    LDA BYTES+1
    STA VAL+1
    LDA BYTES+2
    STA VAL+2
    JSR BIN2BCD
    LDY #7
    LDX #6
ESBYTESLEIDOS01
    LDA RESATASCII,Y
    STA BYTESLEIDOSPR,X
    DEY
    DEX
    BPL ESBYTESLEIDOS01
    RTS
ESBLOQUESLIEDOS
    JSR LIMPIOVAL
    LDA BLOQUES
    STA VAL
    LDA BLOQUES+1
    STA VAL+1
    JSR BIN2BCD
    LDY #7
    LDX #3
ESBLOQUESLIEDOS01
    LDA RESATASCII,Y
    STA BLOQUESLEIDOSPR,X
    DEY
    DEX
    BPL ESBLOQUESLIEDOS01
    RTS
ESMENSAJEINICIO
    LDX #39
ESMENSAJEINICIO01
    LDA MENSAJEINICIO,X
    STA MENSAJES,X
    DEX
    BPL ESMENSAJEINICIO01
    RTS
ESMENSAJECARGANDO
    LDX #39
ESMENSAJECARGANDO01
    LDA MENSAJECARGANDO,X
    STA MENSAJES,X
    DEX
    BPL ESMENSAJECARGANDO01
    RTS
ESMENSAJERETURN
    LDX #39
ESMENSAJERETURN01
    LDA MENSAJERETURN,X
    STA MENSAJES,X
    DEX
    BPL ESMENSAJERETURN01
    RTS
ESMENSAJEINICIANDO
    LDX #39
ESMENSAJEINICIANDO01
    LDA MENSAJEINICIANDO,X
    STA MENSAJES,X
    DEX
    BPL ESMENSAJEINICIANDO01
    RTS
ESMENSAJEPAGINA7
    LDX #39
MENSAJEPAGINA701
    LDA MENSAJEPAGINA7,X
    STA MENSAJES,X
    DEX
    BPL MENSAJEPAGINA701
    RTS
ESMENSAJEPAGINA4
    LDX #39
MENSAJEPAGINA401
    LDA MENSAJEPAGINA4,X
    STA MENSAJES,X
    DEX
    BPL MENSAJEPAGINA401
    RTS
ESMENSAJEPAGINALOAD
    LDX #39
ESMENSAJEPAGINALOAD01
    LDA MENSAJELOADER,X
    STA MENSAJES,X
    DEX
    BPL ESMENSAJEPAGINALOAD01
    RTS
RESETER
    JSR ARMOLOGO
    JSR LIMPIOBANQUEO
    JSR ESPORTB
    JSR ESBANCOS
    JSR LIMPIOTITULO
    JSR LIMPIOOPCIONAL
    JSR LIMPIOFUENTE
    JSR ESMEMORIA
    JSR LIMPIOBYTES
    JSR ESBYTESLEIDOS
    JSR LIMPIOBLOQUES
    JSR ESBLOQUESLIEDOS
    JSR ESMENSAJEINICIO
    LDA #63
    STA TITULOARPR
    STA TITULOOPPR
    STA FUENTEPR
    RTS
;************************************************
;DISPLAY DE INICIO DEL PROGRAMA Y FUNCIONALIDAD
;DIRECTA A TODAS SUS FUNCIONES
;************************************************
DOSPR
	JMP ($0C)
@STARTPR
	JSR DOSPR
STARTPR
    JSR RESETER
    LDX #<DISPLAY
    LDY #>DISPLAY
    STX $230
    STY $231
    LDA #$60
    STA 710
    STA 712
;ACTIVAMOS LA TECLA OPTION EN SEGUNDO PLANO PARA CAMBIO DE SISTEMA NORMAL STAC
    LDY #<VBI
    LDX #>VBI
    LDA #$07
    JSR SETVBV
;INGRESO TITULO ARCHIVO
    LDX #<TITULOARPR
    LDY #>TITULOARPR
    STX PCRSR
    STY PCRSR+1
    JSR RUTLEE
    TYA
	BEQ NOTITLE
	LSR 
	STA RY+1
	LDA #10
	SEC
	SBC RY+1
	STA RY+1
	LDX #$00
	LDY RY+1
WRITE
;************************************************
;AGREGO EL TITULO 01 AL LOADER
;************************************************
	LDA TITULOARPR,X
	STA TITULOPRINCIPALPAGINA7,Y
	INY
	INX
	CPX RY
	BNE WRITE
NOTITLE
;INGRESO TITULO OPCIONAL
    LDX #<TITULOOPPR
    LDY #>TITULOOPPR
    STX PCRSR
    STY PCRSR+1
    JSR RUTLEE

;INGRESO FUENTE DE ARCHIVO A CARGAR
    LDX #<FUENTEPR
    LDY #>FUENTEPR
    STX PCRSR
    STY PCRSR+1
    JSR RUTLEE
    LDY RY
    CPY #1
	BEQ OPENPER
	LDY #19
CONV
	LDA FUENTEPR,Y
	BEQ ?REMAIN
	AND #$7F
	CMP #64
	BCC ADD32
	CMP #96
	BCC SUB64
	BCS ?REMAIN
ADD32
	CLC
	ADC #32
	BCC OKLET
SUB64
	SEC
	SBC #64
?REMAIN
	LDA #$9B
OKLET
	STA FUENTE,Y
	DEY
	BPL CONV
;************************************************
;ABRO PERIFERICO PARA LA CARGA DE ARCHIVO
;************************************************
OPENPER
    JSR CLOSE
    JSR ESMENSAJECARGANDO
    JSR OPEN
    JSR FGET
    JSR CLOSE
    JSR ESMENSAJERETURN
;DAMOS 15 SEGUNDO AL INICIO DE LA CINTA
;DESHABILITAMOS EL SISTEMA OPERATIVO
    LDA #$FE   ;ORIGINAL $FF
    STA $D301
;DEJAMOS EL IRG INICIAL EN 15 SEGUNDOS
    LDA #$03
    STA $FE8D
    LDA #$02
    STA $FE8E
    LDA #$86    ;DURACION DEL TIME DEL IRG 15 SEGUNDOS
    STA $FE8F
    LDA #$8A
    STA $FE90
    JSR OPENC   ;ABRIMOS PERIFERICO
    JSR GAUTO









    LDX #$3C		;CIERRO GRABACION
	LDA #$03		
	STA 53775		;$d20f
	STX $D302
    LDA $FF
    STA PORTB

    LDA #$02
    STA 710
    STA 712










    JMP *
INICIO
    JSR CLOSE
    JSR ROMRAM
    JSR MEM
    LDX # <@STARTPR
    LDY # >@STARTPR
    STX $02
    STY $03
    STA $09
    LDY #$FF
    STY $08
    INY
    STY $0244
    JMP STARTPR
    RUN INICIO
DATADISPLAY
    .BY $00,$E4,$EF,$E7,$E4
    .BY $E1,$F2,$EB,$00,$00
    .BY $73,$6F,$66,$74,$77
    .BY $61,$72,$65,$73,$00
;FUNCION QUE PERMITE EJECUTAR OPTION EN SEGUNDO PLANO
.proc VBI
FIN_SISTEMA=$01 //DESDE 0 A 1
    LDA CONSOL
    CMP CONSOL_ANTERIOR
    BEQ FIN
    STA CONSOL_ANTERIOR
    CMP #$05
    BEQ ESSELECT //ES SELECT
    CMP #$03
    BNE FIN
    LDX SISTEMA
    CPX #FIN_SISTEMA
    BNE NO_FIN_SISTEMA
    LDX #$FF
NO_FIN_SISTEMA
    INX
    STX SISTEMA
    LDA #<ESSTANDART
    LDY #>ESSTANDART
    CPX #$00
    BEQ SIGUESISTEMA
    LDA #<ESSTAC
    LDY #>ESSTAC
SIGUESISTEMA
    STA LOOP_COPIA+1
    STY LOOP_COPIA+2
    LDX #$02
LOOP_COPIA
    LDA ESSTANDART,X
    STA BAUDIOSPR,X
    DEX
    BPL LOOP_COPIA
FIN
    JMP $E462
ESSELECT
    LDX #2
    LDA BYTESBLOQUES
    CMP #$FB
    BEQ ESSELECTFD
    LDA #$FB
    STA BYTESBLOQUES
    LDA #<ES253
    STA FINSELECT+1
    LDA #>ES253
    STA FINSELECT+2
    JMP FINSELECT
ESSELECTFD
    LDA #$80
    STA BYTESBLOQUES
    LDA #<ES128
    STA FINSELECT+1
    LDA #>ES128
    STA FINSELECT+2
FINSELECT
    LDA ES253,X
    STA BYTESPR,X
    DEX
    BPL FINSELECT
    JMP FIN
CONSOL_ANTERIOR 
    .BY $00
.endp
    ICL 'cargar.asm'
    ICL 'grabar.asm'