GENDAT = $47
LOAD
LARGOLOADER     		= [.LEN LOADER]
TITULOLOGO  			= [[LOADER.MENSAJELOAD - LOADER] + LOAD]
TITULOPRINCIPALLOADER  	= [[LOADER.TITULOPRINCIPALLOADER - LOADER] + LOAD]
TITULOOPCIONALLOADER  	= [[LOADER.TITULOOPCIONALLOADER - LOADER] + LOAD]

.PROC LOADER,$6FE
    .BY $55,$55
	LDX #$00
	STX COLDST
	INX
	STX $09
	JMP STARTLOAD
NBYTESLOADER
	.BY 252
FLAGYLOADER
	.BY 0
FINISHLOADER
	.BY 0,0
CONTADORLOADER
	.BY 0
DLISTLOADER
	.BY $70,$70,$70,$46
    .WO MENSAJELOAD
    .BY $70,$02,$70
:9    .BY $02
    .BY $70
    .BY $06,$70,$06,$70,$06,$70,$02,$70,$06
    .BY $41
    .WO DLISTLOADER
MENSAJELOAD
    .SB "--ACA VA EL TITULO--"
    .SB " PROGRAMAS PARA COMPUTADORES ATARI 2024 "
    .SB +32,"QRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRE"
BANQUEOLOAD
    .SB "|**************************************|"  ;38
    .SB "|**************************************|"  ;76
    .SB "|**************************************|"  ;114
    .SB "|**************************************|"  ;152
    .SB "|**************************************|"  ;190
    .SB "|**************************************|"  ;228
    .SB "|**************************************|"  ;266
    .SB +32,"ZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRC"
    .SB +128,"      presenta      "
TITULOOPCIONALLOADER
    .SB "--ACA-VA-EL-TITULO--"
TITULOPRINCIPALLOADER
    .SB "--ACA-VA-EL-TITULO--"
    .SB "  Te faltan "
BYTESRESTANTESLOADER
	.SB "**** bloques para terminar  "
    .SB "  sistemas "
    .SB +128,"dogdark"
    .SB "  "
CDLLOADER
	LDX # <DLISTLOADER
	LDY # >DLISTLOADER
	STX SDLSTL
	STX DLISTL
	STY SDLSTL+1
	STY DLISTL+1
	LDA #$60	;$02C8
	STA COLOR2
	STA COLOR4
	STA COLPF2
	RTS
STARTLOAD
	JSR CDLLOADER
	JMP *	
.ENDP




;*******************
;pagina 7
;*******************
PAG7

PAGINA7LARGO            = [.LEN PAGINA7]
TOTALENCRIPTADOPAGINA7  = [PAGINA7.PANTALLAPAGINA7 - PAGINA7.STACFPAGINA7]
ENCRIPTADOPAGINA7       = [[PAGINA7.PANTALLAPAGINA7 - PAGINA7.STACFPAGINA7] + PAG7]
LOGOPAGINA7             = [[PAGINA7.LOGOPAGINA7 - PAGINA7] + PAG7]
TITULOPRINCIPALPAGINA7  = [[PAGINA7.TITULOPRINCIPALPAGINA7 - PAGINA7] + PAG7]
STACENCRIPT 			= [[PAGINA7.STACFPAGINA7 - PAGINA7] + PAG7]

.PROC PAGINA7,$2000
KEMBUFFER =$B000
INICIOPAG7 
	.BY $00
	.BY [PAGINA7LARGO+127]/128
	.WO INICIOPAG7,PANTALLAPAGINA7
	JSR KEMPAGINA7
	JSR DESENCRIPTOPAGINA7
	LDX SDLSTL
	LDY SDLSTL+1
	STX $BFFC
	STY $BFFD
	LDX # <DLISTPAGINA7
	LDY # >DLISTPAGINA7
	LDA #$00
	STX SDLSTL
	STX DLISTL
	STY SDLSTL+1
	STY DLISTL+1
	STA $41
	JMP $400
KEMPAGINA7
	LDY #$00
KEMLOOP1
	LDA $E000,Y
	STA KEMBUFFER,Y
	LDA $E100,Y
	STA KEMBUFFER+$100,Y
	LDA $E200,Y
	STA KEMBUFFER+$200,Y
	LDA $E300,Y
	STA KEMBUFFER+$300,Y
	INY
	BNE KEMLOOP1
	LDA #>KEMBUFFER
    STA CHBAS
	STA CHBASE
	LDX #$C0
	SEI
	STY $D40E
	STX $CC
	STY $CB
LOOPPAGINA7
	LDA ($CB),Y
	DEC PORTB
	STA ($CB),Y
	INC PORTB
	INY
	BNE LOOPPAGINA7
	INC $CC
	BEQ @EXITPAGINA7
	LDA $CC
	CMP #$D0
	BNE LOOPPAGINA7
	LDA #$D8
	STA $CC
	BNE LOOPPAGINA7
@EXITPAGINA7
	LDA #$e0
    STA CHBAS
	STA CHBASE
	TYA	//y está en cero, según el código de arriba
KEMLOOP2
	STA KEMBUFFER,Y
	STA KEMBUFFER+$100,Y
	STA KEMBUFFER+$200,Y
	STA KEMBUFFER+$300,Y
	INY
	BNE KEMLOOP2
	DEC PORTB
	LDX #$01
	LDY #$4C
	LDA #$13
	STX $EE17
	STY $ED8F
	STA $ED67
	LDX #$80
	LDY #$03
	STX $EBA3
	STY $EBA8
	LDY #$04
	LDA #$EA
NOPERPAGINA7
	STA $ED85,Y
	DEY
	BPL NOPERPAGINA7
	LDY #STACFPAGINA7-STACIPAGINA7
MOVEPAGINA7
	LDA STACIPAGINA7,Y
	STA $ECEF,Y
	DEY
	BPL MOVEPAGINA7
	LDA #$40
	STA NMIEN
	CLI
	CLC
	RTS
STACIPAGINA7
	LDA #$7D
	LDX $62
	BEQ CC0PAGINA7
	LDA #$64
CC0PAGINA7
	CLC
	ADC $EE19,X
	DEY
	BPL CC0PAGINA7
	CLC
	ADC $0312
	SEC
	SBC #$64
	BCC CC3PAGINA7
	STA $0312
	LDY #$02
	LDX #$06
	LDA #$4F
CC2PAGINA7
	ADC $0312
	BCC CC1PAGINA7
	INY
	CLC
CC1PAGINA7
	DEX
	BNE CC2PAGINA7
	STA $02EE
	STY $02EF
	JMP $ED96
CC3PAGINA7
	JMP $ED3D
STACFPAGINA7
	.BY "Dogdark Software 2020"
DLISTPAGINA7
	.BY $70,$70,$70,$70,$70,$70,$70,$70
	.BY $70,$70,$70,$70,$70,$46
	.WO LOGOPAGINA7
	.BY $70,$06,$41
	.WO DLISTPAGINA7
LOGOPAGINA7
:20	.SB " "
TITULOPRINCIPALPAGINA7
:20	.SB " "
PANTALLAPAGINA7
	LDX $BFFC
	LDY $BFFD
	STX SDLSTL
	STY SDLSTL+1
	JMP $700
DESENCRIPTOPAGINA7
    LDX #TOTALENCRIPTADOPAGINA7
DESENCRIPTOPAGINA701
	SEC
    LDA STACFPAGINA7,X
    SBC #$12 ;$FD
    STA STACFPAGINA7,X
    DEX
    BPL DESENCRIPTOPAGINA701
	RTS
;LOOPCITO
	;JMP LOOPCITO
	.SB "DOGDARK 2025"
FINPAGINA7
.ENDP

PAG4

PAGINA4LARGO    = [.LEN PAG4]

.PROC PAGINA4,$03FD
	.BYTE $55,$55,$FE
	LDA PORTB
	ORA #$02
	STA PORTB
	LDA FINPAGINA4
	STA GENDAT
	LDX #$0B
MOVEPAGINA4
	LDA TABLASIOVPAGINA4,X
	STA $0300,X
	DEX
	BPL MOVEPAGINA4
	JSR SIOV
	BMI ERRORPAGINA4
	CLC
	RTS
ERRORPAGINA4
	LDX $BFFC
	LDY $BFFD
	STX $0230
	STY $0231
	LDY #$00
LERPAGINA4
	LDA TABLAPAGINA4,Y
	STA ($58),Y
	INY
	CPY #27
	BNE LERPAGINA4
	LDA #$3C
	STA PACTL
LOOPPAGINA4
	BNE LOOPPAGINA4
TABLAPAGINA4
	.SB "ERROR !!! CARGUE NUEVAMENTE"
TABLASIOVPAGINA4
	.BY $60,$00,$52,$40
	.WO $06FE
	.BY $23,$00
	.WO LARGOLOADER	;l_load
	.BY $00,$80
FINPAGINA4
.ENDP