INITPIRATAS = $5000
.PROC PAGINAPIRATAS,INITPIRATAS
PIRATAS
    STX OPKEYPIRATAS+1
    STY OPKEYPIRATAS+2
    LDX # <DLPASSPIRATAS
    LDY # >DLPASSPIRATAS
    STX $0230
    STX $D402
    STY $0231
    STY $D403
;
    LDA #$31
    STA $0300
;
    AND #$0F
    STA $0301
;
    LDA #$52
    STA $0302
;
    LDA #$40
    STA $0303
;
    LDA # <$0400
    STA $0304
    LDA # >$0400
    STA $0305
;
    LDA #$35
    STA $0306
;
    LDA # <720
    STA 778
    LDA # >720
    STA 779
    JSR $E453   ;Activa Read 
    
    LDY #$05
VERDSKPIRATAS
    LDA $0400,Y
    CMP PARCHEPIRATAS,Y ;QUITAR CLAVE 
    BNE STOPPIRATAS
    DEY
    BPL VERDSKPIRATAS
    INY
    STY RYPIRATAS
    LDX $0406
    STX RYPIRATAS+1
OPKEYPIRATAS
    JSR $FFFF
?VERDSKPIRATAS
    JSR $E456
    LDY RYPIRATAS
    EOR $0407
    CMP $0408,Y
    BEQ SIVERDPIRATAS
    LDA #$EA
    STA STOPPIRATAS-1
SIVERDPIRATAS
    LDA #$03
    STA BFPASSPIRATAS+12,Y
    INC RYPIRATAS
    LDY RYPIRATAS
    CPY RYPIRATAS+1
    BNE ?VERDSKPIRATAS
    RTS
STOPPIRATAS
    LDA # <DLPIRATAS
    STA $0230
    STA $D402
    LDA # >DLPIRATAS
    STA $0231
    STA $D403
    LDY #$00
    STY $90
    STY $91
    LDX # >VBIPIRATAS
    LDY # <VBIPIRATAS
    LDA #$06
    JSR $E45C
    LDA $02C6
    STA $02C8
RAINPIRATAS
    INX
    STX $D40A
    STX $D018
    JMP RAINPIRATAS
VBIPIRATAS
    INC $91
    LDY $91
    CPY #$10
    BNE SALQUIPIRATAS
    LDY #$00
    STY $91
    LDY $90
    LDA BAJAPIRATAS,Y
    EOR #$50
    STA BAJAPIRATAS,Y
    LDA SUBEPIRATAS,Y
    EOR #$60
    STA SUBEPIRATAS,Y
    INY
    STY $90
    CPY #18
    BNE SALQUIPIRATAS
    LDY #$00
    STY $90
SALQUIPIRATAS
    JMP $E462
DLPIRATAS
    .BYTE $70,$70
BAJAPIRATAS
    .BYTE $70,$70,$70,$70,$70
    .BYTE $70,$70,$70,$42
    .WORD DLISTPIRATAS
    .BYTE $02,$02,$02,$06,$06
SUBEPIRATAS
    .BYTE "``````````````````",$02,$02,$02,$41
    .WORD DLPIRATAS
DLISTPIRATAS
    .SB "QRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRE"
    .SB "|  CUIDADO PIRATAS ---> CLAVE : BETA   |"
    .SB "|  SI PERSISTES TE FORMATEARE EL DISCO |"
    .SB "|  ESTES ES EL PRIMERO Y ULTIMO AVISO  |"
    .SB "ZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRC"
    .SB "   diamante omega   "
    .SB "   PHONE: 2386371   "
;
PARCHEPIRATAS
    .BYTE "??????"
DLPASSPIRATAS
    .BYTE "pppppppppppppp",$42
    .WORD BFPASSPIRATAS
    .BYTE $41
    .WORD DLPASSPIRATAS
BFPASSPIRATAS
    .SB " PASSWORD :                             "
RYPIRATAS
    .BYTE 0,0
.ENDP